/**
 * Generated GitHub Actions workflow + repository-local JavaScript Action
 * metadata (P0, default-branch pass).
 *
 * Trigger model (release):
 *  - `on.push.branches[0]` is the STATIC exact-default-branch trigger, ENCODED as
 *    an Actions glob literal (githubActionsBranchLiteral). Never a bare `on: push`.
 *  - The job `if:` also requires `repository.default_branch == github.ref_name`:
 *    after a GitHub-side rename, a stale workflow may still fire for the OLD
 *    branch — this guard skips it (the runtime enforces the same defensively).
 *  - Pre-execution integrity gate: a `run:` step SHA-256-verifies action.yml +
 *    main.cjs BEFORE `uses:`. This is drift detection/reviewability, NOT a
 *    cryptographic trust anchor (a commit changing both runtime and workflow
 *    bypasses it).
 */

import { githubActionsBranchLiteral, yamlQuoteBranch } from "./branch.js";
import { ACTIONS_CHECKOUT_SHA } from "./pins.js";

/** The repository-local JavaScript Action (vendored to .arte-git-card/ci/action.yml). */
export const CI_ACTION_YML = `name: arte-gitcard auto-update
description: Regenerate arte-gitcard cards and push owned artifacts.
runs:
  using: node24
  main: main.cjs
`;

export function workflowPath(): string {
  return ".github/workflows/arte-gitcard.yml";
}

/** Require `actions/checkout` to be pinned to an EXACT lowercase 40-hex SHA. */
export function assertCheckoutPin(checkoutSha: string): string {
  if (!/^[0-9a-f]{40}$/.test(checkoutSha)) {
    throw new Error(
      `invalid actions/checkout pin: expected exactly a 40-char lowercase hex commit SHA, got "${checkoutSha}". ` +
        `Floating tags/branches are never embedded in the workflow.`,
    );
  }
  return checkoutSha;
}

/** Build the workflow YAML for the (Git-ref-validated) default branch. Hashes
 * are SHA-256 of the EXACT LF-normalized bytes the engine writes; they are
 * embedded in the pre-execution verification step. Git-ref validity is the
 * caller's job (`assertGitRefFormat`); here only the empty/too-long pre-check runs. */
export function buildWorkflowYaml(
  branch: string,
  integrity: { actionSha256: string; runtimeSha256: string },
  checkoutSha: string = ACTIONS_CHECKOUT_SHA,
): string {
  if (!/^[0-9a-f]{64}$/.test(integrity.actionSha256) || !/^[0-9a-f]{64}$/.test(integrity.runtimeSha256)) {
    throw new Error("workflow integrity hashes must be 64-char lowercase hex SHA-256 values");
  }
  const sha = assertCheckoutPin(checkoutSha);
  // Static filter is the Actions-glob-ENCODED literal branch (backslashes preserved through the single-quoted YAML scalar).
  const encoded = githubActionsBranchLiteral(branch);
  return `# Generated by arte-gitcard. DO NOT EDIT DIRECTLY.
name: arte-gitcard
on:
  push:
    branches:
      - ${yamlQuoteBranch(encoded)}
permissions: {}
jobs:
  auto-update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.deleted == false && github.ref_name == github.event.repository.default_branch
    concurrency:
      group: \${{ github.workflow }}-\${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@${sha}
        with:
          ref: \${{ github.sha }}
          fetch-depth: 0
          persist-credentials: true
      - name: Verify arte-gitcard vendored action integrity
        run: |
          set -e
          test "$(sha256sum .arte-git-card/ci/action.yml | cut -d' ' -f1)" = "${integrity.actionSha256}" || { echo "arte-git-card/ci/action.yml integrity mismatch (expected ${integrity.actionSha256}); run arte-gitcard github sync"; exit 1; }
          test "$(sha256sum .arte-git-card/ci/main.cjs | cut -d' ' -f1)" = "${integrity.runtimeSha256}" || { echo "arte-git-card/ci/main.cjs integrity mismatch (expected ${integrity.runtimeSha256}); run arte-gitcard github sync"; exit 1; }
      - uses: ./.arte-git-card/ci
`;
}
